"""Builds lib/meals/nutrients.ts from USDA FoodData Central downloads and scripts/fdc/mapping.json.

Download the JSON datasets from https://fdc.nal.usda.gov/download-datasets/ (Foundation, SR Legacy, Survey/FNDDS),
unzip them, then run:
    python3 scripts/fdc/build_nutrients.py path/to/foundation.json path/to/sr_legacy.json path/to/survey.json
"""
import json
import os
import sys

HERE = os.path.dirname(__file__)
OUT = os.path.join(HERE, "..", "..", "lib", "meals", "nutrients.ts")
# USDA nutrient numbers: 208 energy (kcal), 957/958 Atwater energy (used when 208 is missing), 203 protein,
# 205 carbohydrate by difference, 204 total fat
WANTED = ("203", "204", "205", "208", "957", "958")


def load_foods(paths):
    foods = {}
    for path in paths:
        data = json.load(open(path))
        for food in next(iter(data.values())):
            if not isinstance(food, dict):
                continue
            n = {}
            for x in food.get("foodNutrients") or []:
                nut = (x or {}).get("nutrient") or {}
                num, amount = nut.get("number"), (x or {}).get("amount")
                if num in WANTED and amount is not None:
                    if num == "208" and (nut.get("unitName") or "").lower() != "kcal":
                        continue
                    n.setdefault(num, amount)
            kcal = next((n[k] for k in ("208", "958", "957") if k in n), None)
            if kcal is None or not all(k in n for k in ("203", "204", "205")):
                continue
            foods[food["fdcId"]] = {
                "description": food["description"], "dataType": food.get("dataType", ""),
                "kcal": kcal, "protein": n["203"], "carbs": n["205"], "fat": n["204"],
            }
    return foods


def main():
    foods = load_foods(sys.argv[1:])
    mapping = {k: v for k, v in json.load(open(os.path.join(HERE, "mapping.json"))).items() if not k.startswith("_")}
    rows = []
    for item, spec in sorted(mapping.items()):
        ids = spec.get("blend") or [spec["fdc"]]
        missing = [i for i in ids if i not in foods]
        if missing:
            sys.exit(f"{item}: fdcId {missing} not found in the given files")
        picked = [foods[i] for i in ids]
        scale = spec.get("scale", 1)
        per100 = {k: round(sum(f[k] for f in picked) / len(picked) * scale, 2) for k in ("kcal", "protein", "carbs", "fat")}
        rows.append({
            "item": item, "fdcIds": ids, "description": " + ".join(f["description"] for f in picked),
            **per100, **({"standIn": spec["stand_in"]} if "stand_in" in spec else {}),
        })
    body = ",\n".join("  " + json.dumps(r["item"]) + ": " + json.dumps({k: v for k, v in r.items() if k != "item"}) for r in rows)
    with open(OUT, "w") as f:
        f.write(
            "// GENERATED by scripts/fdc/build_nutrients.py from USDA FoodData Central (public domain, CC0).\n"
            "// Do not edit by hand: change scripts/fdc/mapping.json and rerun the script.\n"
            "// Values are per 100 g. standIn explains foods USDA doesn't list, where the closest USDA food is used.\n\n"
            "export type Nutrients = { kcal: number; protein: number; carbs: number; fat: number };\n"
            "export type IngredientNutrients = Nutrients & { fdcIds: number[]; description: string; standIn?: string };\n\n"
            "export const NUTRIENTS_PER_100G: Record<string, IngredientNutrients> = {\n" + body + ",\n};\n"
        )
    print(f"wrote {len(rows)} ingredients to {os.path.relpath(OUT)}")


main()
